#!/bin/bash
#It compresses file.

compress_and_uncompress_zip_files()
{
    read -p "What you want to do, (zip) or (unzip) files." action
    case $action in
        zip )
            zip -r $file_name $file_source;;
        unzip)
            unzip $file_name -d $file_source;;
        *)
            echo "UNKNOWN COMMAND, only (zip) and (unzip) command available";;
    esac
}

compress_files(){
local ext="${file_name##*.}"
    case $ext in
        gz)
            tar -czf $file_name $file_source;;
        zip)
            compress_and_uncompress_zip_files;;
        *)
            echo "No format to compress files to.";;
    esac
}


execute_program(){
read -p "Enter name with extension to compress as first argument and source directory as second: " file_name file_source
if [[ $file_name && $file_source ]]; then
    compress_files
else
    echo "Enter name and source"   
fi
}
    
if [[ $1 == "--version" ]]; then
    echo "compress ver. $(pacman -Qi compress | grep -Po '(?<=^Version).*' | sed "s/^\s*: //" )" 
elif [[ $1 == "" ]]; then
    execute_program
else
    echo "UNKNOWN PREFIX"
fi
